spring:
  mail:
    host: smtp.163.com
    username: renai_2568092604@163.com
    password: VXWQRZEPLRJRUVQE
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
  security:
    jwt:
      key: renaisfirstproject
      expire: 7
    filter:
      order: -100
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
